-- NOTICE: The canonical per-DB DDL files now live inside the server-starter jar on the classpath:
--
--   ticker-server-spring-boot-starter/src/main/resources/db/ticker-history-schema-h2.sql
--   ticker-server-spring-boot-starter/src/main/resources/db/ticker-history-schema-mysql.sql
--   ticker-server-spring-boot-starter/src/main/resources/db/ticker-history-schema-postgresql.sql
--
-- These are the single source of truth. The schema is auto-applied at startup when
-- ticker.history.enabled=true and ticker.history.init-schema=true (the default).
-- Set ticker.history.init-schema=false to skip auto-creation; then run the matching DDL file
-- manually as a one-time step before starting the collector.
--
-- Example env-var wiring in application.yml (credentials must come from env — guardrail #5):
--
--   ticker:
--     history:
--       enabled: true
--       db: mysql
--       url: jdbc:mysql://db-host:3306/ticker
--       username: ${TICKER_DB_USER}
--       password: ${TICKER_DB_PASS}
--
-- Add the MySQL driver at runtime (NOT bundled in the server-starter by default):
--   implementation("com.mysql:mysql-connector-j")
